#!/usr/bin/env python3
"""
Build a published module question bank (src/content/*.mjs) from extracted
question JSON.

One generator serves every published bank; per-bank differences (title,
version, module groups/order/titles, technical vs non-technical modules,
paper-shape note) live in a small JSON config rather than in the code.
RSA keeps its historical behaviour: with no config argument the built-in
RSA config is used, and `scripts/rsa-bank-config.json` (committed) is the
same config written out, so a regeneration of the RSA bank reproduces the
committed file byte for byte.

Pipeline (RSA bank):
    node scripts/extract-question-bank-from-xlsx.mjs \\
        "Question bank 1.4.xlsx"  data/bank.json
    python3 scripts/build-question-bank.py data/bank.json \\
        src/content/rsa-question-bank.mjs 1.4 [scripts/rsa-bank-config.json]

Pipeline (AI/BI & Genie bank):
    node scripts/extract-ai-bi-bank-from-xlsx.mjs \\
        "AI BI G Question bank 1.1.xlsx"  data/ai-bi-bank.json
    python3 scripts/build-question-bank.py data/ai-bi-bank.json \\
        src/content/ai-bi-genie-question-bank.mjs 1.1 scripts/ai-bi-bank-config.json

The emitted module is organised MODULE -> FAMILY -> QUESTION, which is also
the order questions appear in the file, so the catalogue reads the same way
the Admin UI presents it and a new question has exactly one place to go.

A family name is only unique *within* a module, so families are addressed by
the compound id `<MODULE>:<family-slug>` (e.g. `T05:delta-lake-physical-design`),
which is what makes "add this question to that family" unambiguous.

Usage:  python3 scripts/build-question-bank.py <bank.json> <output.mjs> [version] [config.json]
"""
import json
import re
import sys
from collections import OrderedDict

# ---------------------------------------------------------------------------
# Built-in RSA config: identical to scripts/rsa-bank-config.json. Kept inline
# so the historical three-argument invocation keeps working, and the committed
# config file exists so regeneration is reproducible from the repo alone.
# ---------------------------------------------------------------------------
RSA_CONFIG = {
    'title': 'ECOD RSA Question Bank',
    'version': '1.4',
    'header': [
        ' * ECOD RSA Question Bank v{version} - the published, finalized catalogue.',
        ' *',
        ' * Organised MODULE -> FAMILY -> QUESTION. Generated by',
        ' * scripts/build-question-bank.py from the published source workbook/CSV;',
        ' * edit the generator (or the Admin UI), not this file by hand.',
        ' *',
        ' *   T01-T10   Technical     3 objective + 1 open served per module',
        ' *   C01-C04   Consulting    1 open served per module',
        ' *   P01-P04   Professional  1 open served per module',
        ' *   F01-F02   Foundation    1 open served per module',
        ' *',
        ' * Every generated test is (10 x 4) + (10 x 1) = 50 questions, shuffled so',
        ' * objective and open questions interleave rather than arriving in blocks.',
        ' * See src/core/test-generation.mjs for the selection logic.',
        ' *',
        ' * FAMILIES ARE SCOPED TO A MODULE. A family name is not unique on its own -',
        ' * "Advanced Technical Judgment" exists in all ten technical modules - so the',
        ' * addressable unit is the compound id `<MODULE>:<family-slug>`, e.g.',
        ' * `T05:delta-lake-physical-design`. A new question is added to exactly one',
        ' * such family, and `family_id` is what pins it there.',
        ' *',
        ' * `needs_option_review` marks an objective question that still needs an admin',
        ' * to complete its distractor text. The published v1.4 workbook carries all',
        ' * four options, so published objectives no longer set it.',
    ],
    'groups': [
        ('technical', 'Technical', 1,
         'Databricks platform depth: architecture, engineering, governance, performance and AI.'),
        ('consulting', 'Consulting & Client Skills', 2,
         'Discovery, solution options, objection handling and engagement accountability.'),
        ('professional', 'Professional & Communication', 3,
         'Executive communication, listening, presentation and technical translation.'),
        ('foundation', 'Foundation & Integrated Judgment', 4,
         'Databricks value, the RSA role and whole-engagement judgment.'),
    ],
    'moduleTitles': {
        'F01': 'Databricks Value & RSA Role',
        'F02': 'Integrated Client Engagement & Validation',
        'T01': 'Databricks Architecture, Lakehouse & Data Intelligence',
        'T02': 'Data Ingestion, Streaming & Change Processing',
        'T03': 'Lakeflow Pipelines, Jobs & Data Quality',
        'T04': 'SQL, PySpark & Data Engineering',
        'T05': 'Delta Lake, Performance, Compute & Cost Optimization',
        'T06': 'Unity Catalog, Security & Data Governance',
        'T07': 'APIs, Integration & Serving',
        'T08': 'Migration, Troubleshooting & Production Operations',
        'T09': 'AI/BI, Semantic Layer & Genie',
        'T10': 'GenAI, RAG & Agent Operations',
        'C01': 'Discovery & Requirement Structuring',
        'C02': 'Solution Options & Commercial Judgment',
        'C03': 'Objection Handling & Consultative Influence',
        'C04': 'Engagement Communication & Accountability',
        'P01': 'Executive Communication & Value Framing',
        'P02': 'Active Listening & Conflict Navigation',
        'P03': 'Architecture Presentation & Whiteboarding',
        'P04': 'Technical-to-Business Translation',
    },
    'groupOf': {'T': 'technical', 'C': 'consulting', 'P': 'professional', 'F': 'foundation'},
    'technicalModules': ['T01', 'T02', 'T03', 'T04', 'T05', 'T06', 'T07', 'T08', 'T09', 'T10'],
    # [module key, display order] pairs. RSA historically numbered T01-T10 as
    # 11-20, C01-C04 as 21-24, P01-P04 as 31-34 and F01-F02 as 41-42; the
    # numbers are part of the committed generated file, so they stay explicit.
    'moduleOrder': [
        ['T01', 11], ['T02', 12], ['T03', 13], ['T04', 14], ['T05', 15],
        ['T06', 16], ['T07', 17], ['T08', 18], ['T09', 19], ['T10', 20],
        ['C01', 21], ['C02', 22], ['C03', 23], ['C04', 24],
        ['P01', 31], ['P02', 32], ['P03', 33], ['P04', 34],
        ['F01', 41], ['F02', 42],
    ],
}


def slug(text):
    return re.sub(r'-+', '-', re.sub(r'[^a-z0-9]+', '-', text.lower())).strip('-')


def flat(text):
    """Collapse whitespace - used in generated comments."""
    return re.sub(r'\s+', ' ', str(text or '')).strip()


def js(value):
    """Emit a JS single-quoted string literal."""
    text = re.sub(r'\s+', ' ', str(value or '')).strip()
    return "'" + text.replace('\\', '\\\\').replace("'", "\\'") + "'"


def family_role(questions):
    """What a family supplies, which drives the default type when authoring."""
    has_objective = any(q['objective'] for q in questions)
    has_open = any(not q['objective'] for q in questions)
    if has_objective and has_open:
        return 'mixed'
    return 'objective' if has_objective else 'open'


def build(bank_path, out_path, version=None, config=None):
    if config is None:
        config = RSA_CONFIG
    if version is None:
        version = config.get('version')
    version = str(version)
    titles = config['moduleTitles']
    order_pairs = config['moduleOrder']
    order_index = {key: i for i, (key, _) in enumerate(order_pairs)}
    order_value = {key: num for key, num in order_pairs}
    technical = set(config['technicalModules'])
    group_of = config['groupOf']

    bank = json.load(open(bank_path, encoding='utf-8'))

    # Modules present in the bank but absent from the config are a config
    # drift, not something to guess at - fail loudly.
    bank_modules = {q['module'] for q in bank}
    unknown = bank_modules - set(order_index)
    if unknown:
        sys.exit(f"config lists no order for module(s): {', '.join(sorted(unknown))}")

    # ---- group questions: module -> family -> [questions] --------------
    modules = OrderedDict()
    for question in bank:
        key = question['module']
        modules.setdefault(key, OrderedDict())

    for key in sorted(modules, key=lambda k: order_index[k]):
        rows = [q for q in bank if q['module'] == key]
        families = OrderedDict()
        # Objective-holding families first (a module's core), then the open
        # families alphabetically - stable, and it reads well in the UI.
        for name in sorted(
            {q['question_family'] for q in rows},
            key=lambda n: (
                not any(q['objective'] for q in rows if q['question_family'] == n),
                n,
            ),
        ):
            members = [q for q in rows if q['question_family'] == name]
            members.sort(key=lambda q: (not q['objective'], q['id']))
            families[name] = members
        modules[key] = families

    lines = []
    w = lines.append

    w('/**')
    for raw in config['header']:
        w(raw.format(version=version))
    w(' */')
    w('')
    w(f"export const QUESTION_BANK_VERSION = '{version}';")
    w('')
    w('/** Top-level grouping of modules (not to be confused with question families). */')
    w('export const MODULE_GROUPS = [')
    for key, name, ord_, description in config['groups']:
        w(f"  {{ key: '{key}', name: {js(name)}, order: {ord_},")
        w(f"    description: {js(description)} }},")
    w('];')
    w('')

    # ---- modules, each carrying its own families -----------------------
    w('/**')
    w(' * Every module, with the families that live inside it. `role` says what a')
    w(' * family supplies, so the question editor can default the answer type:')
    w(" * 'objective', 'open', or 'mixed'.")
    w(' */')
    w('export const MODULES = [')
    for key in sorted(modules, key=lambda k: order_index[k]):
        families = modules[key]
        group = group_of[key[0]]
        is_technical = 'true' if key in technical else 'false'
        w(f"  {{ key: '{key}', name: {js(titles[key])}, group: '{group}', order: {order_value[key]},")
        w(f"    technical: {is_technical},")
        w('    families: [')
        for name, members in families.items():
            # Counts describe what the family actually holds, so a family row
            # and its drill-down can never disagree.
            objective = sum(1 for q in members if q['objective'])
            w(f"      {{ id: '{key}:{slug(name)}', key: '{slug(name)}', name: {js(name)},")
            w(f"        role: '{family_role(members)}', objective: {objective}, open: {len(members) - objective} }},")
        w('    ] },')
    w('];')
    w('')

    # ---- the questions themselves, module by module, family by family ---
    w('/** Every question, ordered by module and then by family. */')
    w('export const QUESTIONS = [')
    for key in sorted(modules, key=lambda k: order_index[k]):
        families = modules[key]
        total = sum(len(v) for v in families.values())
        w(f'  // ==================================================================')
        w(f'  // {key} - {flat(titles[key])}')
        w(f'  // {total} question{"s" if total != 1 else ""}'
          f' across {len(families)} famil{"y" if len(families) == 1 else "ies"}')
        w(f'  // ==================================================================')
        for name, members in families.items():
            objective = sum(1 for q in members if q['objective'])
            w(f'  // -- {key} / {flat(name)} '
              f'({objective} objective / {len(members) - objective} open)')
            for q in members:
                w('  {')
                w(f"    id: '{q['id']}', module: '{key}',")
                w(f"    family_id: '{key}:{slug(name)}', family: {js(name)},")
                w(f"    type: '{'objective' if q['objective'] else 'open'}', source_type: {js(q['type'])},")
                w(f"    difficulty: {q['difficulty']}, band: {js(q['band'])}, mode: {js(q['mode'])},")
                w(f"    minutes: {q['minutes']}, status: {js(q['status'])}, version: {js(q['version'])},")
                w(f"    randomizable: {'true' if q['randomizable'] else 'false'},")
                w(f"    prompt: {js(q['prompt'])},")
                if q['objective']:
                    w('    options: [')
                    for letter in sorted(q['options']):
                        w(f"      {{ id: '{letter.lower()}', label: {js(q['options'][letter])} }},")
                    w('    ],')
                    w(f"    correct_option_ids: ['{(q['correct'] or 'a').lower()}'],")
                    w(f"    rationale: {js(q['rationale'])},")
                    w(f"    needs_option_review: {'true' if q['needs_option_review'] else 'false'},")
                else:
                    w(f"    probes: [{', '.join(js(p) for p in q['probes'])}],")
                    w(f"    rubric: {js(q['expected_evidence'])},")
                w(f"    red_flags: {js(q['red_flags'])},")
                w(f"    gap_tag: {js(q['gap_tag'])},")
                w(f"    enrichment: {js(q['enrichment'])},")
                w('  },')
    w('];')
    w('')
    w('/** Every family in the bank, flattened, for lookup by compound id. */')
    w('export const FAMILIES = MODULES.flatMap((m) =>')
    w('  m.families.map((f) => ({ ...f, module: m.key, group: m.group })));')
    w('')
    w('/** Resolve a compound family id (e.g. "T05:cost-finops"). */')
    w('export function findFamily(familyId) {')
    w('  return FAMILIES.find((f) => f.id === familyId) || null;')
    w('}')
    w('')

    with open(out_path, 'w', encoding='utf-8') as fh:
        fh.write('\n'.join(lines) + '\n')

    pairs = sum(len(v) for v in modules.values())
    objective = [q for q in bank if q['objective']]
    review = sum(1 for q in objective if q.get('needs_option_review'))
    print(f'v{version}: {len(bank)} questions | {len(modules)} modules | '
          f'{pairs} module-family pairs | {review}/{len(objective)} objective '
          f'items clipped by the source export -> {out_path}')


if __name__ == '__main__':
    if not 3 <= len(sys.argv) <= 5:
        sys.exit(__doc__)
    cfg = None
    if len(sys.argv) >= 5:
        cfg = json.load(open(sys.argv[4], encoding='utf-8'))
    build(sys.argv[1], sys.argv[2], *(sys.argv[3:4]), config=cfg)
